# Generated by Django 5.0.7 on 2024-07-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя продукта')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('image', models.ImageField(upload_to='image_product')),
                ('count', models.IntegerField(verbose_name='количество')),
            ],
        ),
    ]
