# Generated by Django 5.0.7 on 2024-07-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_product'),
        ),
    ]
